coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%

ignore:
  - "*/migrations/*"
  - "*/venv/*"
  - "*/env/*"
  - "manage.py"
  - "*/settings/*"
  - "*/tests/*"
