version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - djangochatify_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - djangochatify_network

networks:
  djangochatify_network:
    driver: bridge